name: Python application 2

on:
  push:
    branches:
      - "main"
      - "release"
  pull_request:
    branches:
      - "main"
      - "release"
      - "develop"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print user information
      run: |
        echo "ФИО: Корень Полина Алексеевна"
        echo "Группа: M3110"
        echo "GitHub Nickname: ${{ github.actor }}"

    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check current directory
      run: pwd

    - name: List files in the repository
      run: ls -R

    - name: Run unit tests
      run: |
        # Убедитесь, что директория tests существует и доступна
        if [ -d "tests" ]; then
          python -m unittest discover -s tests
        else
          echo "Directory 'tests' does not exist"
          exit 1
        fi

    - name: Lint the code
      run: |
        pip install flake8
        flake8 .
